In [303]:
#importing all Basic Libraries 

import numpy as np         
import pandas as pd
import itertools
from sklearn.model_selection import train_test_split
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.linear_model import PassiveAggressiveClassifier
from sklearn.svm import SVC
from sklearn.naive_bayes import MultinomialNB
from sklearn.metrics import accuracy_score, classification_report,confusion_matrix

In [304]:
#creating DataFrame and loading data

df=pd.read_csv("/content/news.csv")  
df.head()

Unnamed: 0                                              title  \
0        8476                       You Can Smell Hillary’s Fear   
1       10294  Watch The Exact Moment Paul Ryan Committed Pol...   
2        3608        Kerry to go to Paris in gesture of sympathy   
3       10142  Bernie supporters on Twitter erupt in anger ag...   
4         875   The Battle of New York: Why This Primary Matters   

                                                text label  
0  Daniel Greenfield, a Shillman Journalism Fello...  FAKE  
1  Google Pinterest Digg Linkedin Reddit Stumbleu...  FAKE  
2  U.S. Secretary of State John F. Kerry said Mon...  REAL  
3  — Kaydee King (@KaydeeKing) November 9, 2016 T...  FAKE  
4  It's primary day in New York and front-runners...  REAL

In [305]:
df.shape        #shape of the data

(6335, 4)

In [306]:
df.info()       #all info about the data


<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6335 entries, 0 to 6334
Data columns (total 4 columns):
 #   Column      Non-Null Count  Dtype 
---  ------      --------------  ----- 
 0   Unnamed: 0  6335 non-null   int64 
 1   title       6335 non-null   object
 2   text        6335 non-null   object
 3   label       6335 non-null   object
dtypes: int64(1), object(3)
memory usage: 198.1+ KB


In [307]:
df.head()          #disply first 5 row of the data

Unnamed: 0                                              title  \
0        8476                       You Can Smell Hillary’s Fear   
1       10294  Watch The Exact Moment Paul Ryan Committed Pol...   
2        3608        Kerry to go to Paris in gesture of sympathy   
3       10142  Bernie supporters on Twitter erupt in anger ag...   
4         875   The Battle of New York: Why This Primary Matters   

                                                text label  
0  Daniel Greenfield, a Shillman Journalism Fello...  FAKE  
1  Google Pinterest Digg Linkedin Reddit Stumbleu...  FAKE  
2  U.S. Secretary of State John F. Kerry said Mon...  REAL  
3  — Kaydee King (@KaydeeKing) November 9, 2016 T...  FAKE  
4  It's primary day in New York and front-runners...  REAL

In [308]:
#DECLARING X AND Y VARIABLES FOR SPLITING IN TRAIN_TEST_SPLIT

x=df["text"]  
y=df.label      

In [309]:
#train_test_split feature are using for spliting the data for traning and testing

x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=.2,random_state=1)

In [310]:
# Applying the Tfidf vectorizer
vect=TfidfVectorizer(stop_words='english',max_df=0.1)
x_train_vect=vect.fit_transform(x_train)
x_test_vect=vect.transform(x_test)

#**1:Passive Aggressive Classifier**

In [311]:
#APPLYING Passive Aggressive Classifier

pac=PassiveAggressiveClassifier(max_iter=50)
pac.fit(x_train_vect,y_train)
y_pred_1=pac.predict(x_test_vect)
y_pred_1

array(['REAL', 'FAKE', 'FAKE', ..., 'REAL', 'REAL', 'REAL'], dtype='<U4')

In [312]:
#accuracy of the model

score_1=accuracy_score(y_pred_1,y_test)
print(f'The Passive Aggressive Classifier Accuracy is: {round(score_1*100,2)}%')

The Passive Aggressive Classifier Accuracy is: 93.13%


In [313]:
#classification report of the model
print(classification_report(y_pred_1,y_test))

              precision    recall  f1-score   support

        FAKE       0.93      0.94      0.93       644
        REAL       0.94      0.92      0.93       623

    accuracy                           0.93      1267
   macro avg       0.93      0.93      0.93      1267
weighted avg       0.93      0.93      0.93      1267



In [314]:
#confusion matrix of the model

confusion_matrix(y_test,y_pred_1, labels=['FAKE','REAL'])


array([[604,  47],
       [ 40, 576]])

#**2:SUPPORT VECTOR MACHINE**

In [315]:
# Applying the Count vectorizer 

svc=SVC()
svc.fit(x_train_vect,y_train)
y_pred_2=svc.predict(x_test_vect)
y_pred_2

array(['REAL', 'FAKE', 'FAKE', ..., 'FAKE', 'REAL', 'REAL'], dtype=object)

In [316]:
#accuracy of the model

score_2=accuracy_score(y_pred_2,y_test)
print(f'The Support Vector Machine Accuracy is: {round(score_2*100,2)}%')

The Support Vector Machine Accuracy is: 92.74%


In [317]:
#classification report of the model
print(classification_report(y_pred_2,y_test))

              precision    recall  f1-score   support

        FAKE       0.95      0.91      0.93       675
        REAL       0.91      0.94      0.92       592

    accuracy                           0.93      1267
   macro avg       0.93      0.93      0.93      1267
weighted avg       0.93      0.93      0.93      1267



In [318]:
#confusion matrix of the model

confusion_matrix(y_test,y_pred_2, labels=['FAKE','REAL'])


array([[617,  34],
       [ 58, 558]])

# **3:NAIVE_BAYES WITH MultinomialNB**



In [319]:
#APPLYING Passive Aggressive Classifier

nb=MultinomialNB()
nb.fit(x_train_vect,y_train)
y_pred_3=nb.predict(x_test_vect)
y_pred_3

array(['REAL', 'FAKE', 'FAKE', ..., 'REAL', 'REAL', 'REAL'], dtype='<U4')

In [320]:
#accuracy of the model

score_3=accuracy_score(y_pred_3,y_test)
print(f'The MultinomialNB Accuracy is: {round(score_3*100,2)}%')

The MultinomialNB Accuracy is: 83.19%


In [321]:
#classification report of the model
print(classification_report(y_pred_3,y_test))

              precision    recall  f1-score   support

        FAKE       0.70      0.96      0.81       472
        REAL       0.97      0.75      0.85       795

    accuracy                           0.83      1267
   macro avg       0.84      0.86      0.83      1267
weighted avg       0.87      0.83      0.83      1267



In [322]:
#confusion matrix of the model

confusion_matrix(y_test,y_pred_3, labels=['FAKE','REAL'])

array([[455, 196],
       [ 17, 599]])

#Accuracy Report of all Classifier

In [323]:
print('--'*30)
PAC=print(f'The PassivePassive Aggressive Classifier Accuracy is: {round(score_1*100,2)}%')
print('--'*30)
svc=print(f'The Support Vector Machine Accuracy is: {round(score_2*100,2)}%')
print('--'*30)
NB=print(f'The Passive MultinomialNB Accuracy is: {round(score_3*100,2)}%')

------------------------------------------------------------
The PassivePassive Aggressive Classifier Accuracy is: 93.13%
------------------------------------------------------------
The Support Vector Machine Accuracy is: 92.74%
------------------------------------------------------------
The Passive MultinomialNB Accuracy is: 83.19%


Here we can Clearly see the Passive Aggressive Classifier is better accuracy than others SVC and MultinomialNB. So the Passive Aggressive Classifier is  best model for this Data.